### ISSUE TITLE
`ReferenceError: countriesWS is not defined`

### ISSUE THREAD

**Issue by XP1** [fkereki/NodeJsRestful#1]
**`ReferenceError: countriesWS is not defined`**

I get an exception when I run `node restify_rest.js`.

Here is the message:

```
restify_rest.js:8
server.get(/^\/countries\/?(.*)/, countriesWS);
                                  ^
ReferenceError: countriesWS is not defined
    at Object.<anonymous> (restify_rest.js:8:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

Here are the lines of code:
https://github.com/fkereki/NodeJsRestful/commit/2d5e8fc5c057aace91a63764ac87ccaa9b08675c#L4R8

Is there code missing? I cannot find `countriesWS` anywhere else.

**Comment by fkereki** [comment]
The right command is node router_rest.js -- restify_rest.js was an experiment, and shouldn't be included. I'll delete it. Thanks for catching the problem!
